name: calvin-act
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pytorch
  - torchvision
  - pytorch-cuda=12.1
  - numpy
  - pandas
  - matplotlib
  - pyyaml
  - tqdm
  - h5py
  - imageio
  - imageio-ffmpeg
  - pip:
      - lerobot
      - datasets
      - huggingface_hub
      - wandb
      - safetensors
      - einops
      - opencv-python
